# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

version: '3' 

networks:
  gnmic-net:
    driver: bridge

services:
  gnmic1: &gnmic
    image: ghcr.io/openconfig/gnmic:latest
    container_name: gnmic1
    volumes:
      - ./gnmic.yaml:/app/gnmic.yaml
    command: "subscribe --config /app/gnmic.yaml"
    environment:
      - GNMIC_API=:7890
      - GNMIC_CLUSTERING_INSTANCE_NAME=gnmic1
      - GNMIC_CLUSTERING_SERVICE_ADDRESS=gnmic1
      - GNMIC_OUTPUTS_OUTPUT1_LISTEN=gnmic1:9804
    networks:
      - gnmic-net
    ports:
      - 7890:7890
      - 9804:9804
    depends_on:
      - consul-agent 

  gnmic2:
    <<: *gnmic
    container_name: gnmic2
    environment:
      - GNMIC_API=:7891
      - GNMIC_CLUSTERING_INSTANCE_NAME=gnmic2
      - GNMIC_CLUSTERING_SERVICE_ADDRESS=gnmic2
      - GNMIC_OUTPUTS_OUTPUT1_LISTEN=gnmic2:9805
    ports:
      - 7891:7891
      - 9805:9805

  gnmic3:
    <<: *gnmic
    container_name: gnmic3
    environment:
      - GNMIC_API=:7892
      - GNMIC_CLUSTERING_INSTANCE_NAME=gnmic3
      - GNMIC_CLUSTERING_SERVICE_ADDRESS=gnmic3
      - GNMIC_OUTPUTS_OUTPUT1_LISTEN=gnmic3:9806
    ports:
      - 7892:7892
      - 9806:9806

  consul-agent:
    image: consul:latest
    container_name: consul
    networks:
      - gnmic-net
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0    

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=debug'
    ports:
      - 9090:9090
    networks:
      - gnmic-net

volumes:
  prometheus-data:
