# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: gnmic-svc
  labels:
    app: gnmic
spec:
  ports:
  - name: http
    port: 9804
    protocol: TCP
    targetPort: 9804
  selector:
    app: gnmic
  clusterIP: None
